package com.parkingdetection.domain

import kotlin.test.*

class ParkingDetectionTest {
    @Test fun driveParkBluetoothWalkAwayReachesParked() { val engine=ParkingDetectionStateMachine(); engine.onActivity(ActivityType.IN_VEHICLE); engine.onActivity(ActivityType.IN_VEHICLE); engine.onLocation(LocationSample(40.0,-73.0,8.0,speedMetersPerSecond=18.0,timestampMillis=1, bluetoothConnected=true)); engine.onLocation(LocationSample(40.0,-73.0,6.0,speedMetersPerSecond=0.2,timestampMillis=2)); val candidate=engine.evaluate(DetectionSignals(wasInVehicle=true,maxTripSpeedKmh=65.0,lowSpeedDurationSeconds=120,transitionedVehicleToWalking=true,knownBluetoothDisconnected=true,walkingAwayDistanceMeters=35.0,locationStable=true,gpsAccuracyMeters=8.0)); assertEquals(DetectionState.PARKED, candidate.state); assertTrue(candidate.score >= 70); assertTrue(DetectionReason.COMBINED_SENSOR_FUSION in candidate.reasons) }
    @Test fun redSignalIsRejectedByDrivingResume() { val scorer=ConfidenceScorer(); val (score, _)=scorer.score(DetectionSignals(wasInVehicle=true,maxTripSpeedKmh=40.0,lowSpeedDurationSeconds=20,stopDurationSeconds=30,drivingResumed=true,gpsAccuracyMeters=8.0,majorRoadOrJunction=true)); assertTrue(score < 30) }
    @Test fun poorGpsCanStillUseFallbackButPenalizesConfidence() { val scorer=ConfidenceScorer(); val (score, reasons)=scorer.score(DetectionSignals(wasInVehicle=true,maxTripSpeedKmh=30.0,lowSpeedDurationSeconds=120,transitionedVehicleToWalking=true,knownBluetoothDisconnected=true,walkingAwayDistanceMeters=25.0,gpsAccuracyMeters=120.0,poorGpsFallbackAvailable=true)); assertTrue(score >= 70); assertTrue(DetectionReason.POOR_GPS_FALLBACK in reasons) }
    @Test fun bufferChoosesPreWalkingAccurateLowSpeedPoint() { val buffer=LocationBuffer(); buffer.add(LocationSample(1.0,1.0,50.0,speedMetersPerSecond=0.1,timestampMillis=1)); buffer.add(LocationSample(1.1,1.1,5.0,speedMetersPerSecond=1.2,timestampMillis=2)); buffer.add(LocationSample(1.2,1.2,3.0,speedMetersPerSecond=1.5,timestampMillis=3)); assertEquals(2, buffer.best(beforeMillis=2)!!.timestampMillis) }
    @Test fun duplicateGuardPreventsNearbyRecentRecord() { val guard=DuplicateParkingGuard(); val now=1000L; val record=ParkingRecord("r1",null,40.0,-73.0,8.0,parkedAtMillis=900,detectedAtMillis=900,detectionMethods=setOf(DetectionReason.MANUAL),confidenceScore=100,isAutomatic=false,isConfirmed=true,createdAtMillis=900,updatedAtMillis=900); assertTrue(guard.isDuplicate(LocationSample(40.0001,-73.0001,7.0,speedMetersPerSecond=0.0,timestampMillis=now), record, now)) }
}
