import Foundation

public enum DetectionState: String, Codable, Sendable { case idle, possibleVehicleJourney, inVehicle, possibleParking, parkingConfirmation, parked, userRejected, drivingResumed }
public enum ActivityType: String, Codable, Sendable { case unknown, still, walking, onFoot, inVehicle, running, cycling }
public enum DetectionReason: String, Codable, Sendable, Hashable { case activityTransition, bluetoothDisconnect, carPlayDisconnect, speedAndLocation, walkingAway, manual, combinedSensorFusion, poorGpsFallback }
public struct DetectionConfiguration: Codable, Sendable { public var confidenceThreshold = 70; public var minDrivingSpeedKmh = 15.0; public var lowSpeedConfirmationSeconds: Int = 90; public var maxGoodAccuracyMeters = 50.0; public init() {} }
public struct DetectionSignals: Sendable { public var wasInVehicle=false; public var maxTripSpeedKmh=0.0; public var lowSpeedDurationSeconds=0; public var transitionedVehicleToWalking=false; public var knownBluetoothDisconnected=false; public var walkingAwayDistanceMeters=0.0; public var locationStable=false; public var stopDurationSeconds=0; public var drivingResumed=false; public var gpsAccuracyMeters=999.0; public var majorRoadOrJunction=false; public var poorGpsFallbackAvailable=false; public init() {} }
public struct LocationSample: Codable, Sendable { public let latitude: Double; public let longitude: Double; public let accuracy: Double; public let speedMetersPerSecond: Double; public let timestamp: Date; public let activityType: ActivityType; public let activityConfidence: Int; public let bluetoothConnected: Bool; public init(latitude: Double, longitude: Double, accuracy: Double, speedMetersPerSecond: Double, timestamp: Date, activityType: ActivityType = .unknown, activityConfidence: Int = 0, bluetoothConnected: Bool = false) { self.latitude=latitude; self.longitude=longitude; self.accuracy=accuracy; self.speedMetersPerSecond=speedMetersPerSecond; self.timestamp=timestamp; self.activityType=activityType; self.activityConfidence=activityConfidence; self.bluetoothConnected=bluetoothConnected } }
public struct ParkingRecord: Identifiable, Codable, Sendable { public let id: UUID; public var vehicleId: UUID?; public var latitude: Double; public var longitude: Double; public var accuracy: Double; public var address: String?; public var placeName: String?; public var parkedAt: Date; public var detectedAt: Date; public var detectionMethods: Set<DetectionReason>; public var confidenceScore: Int; public var isAutomatic: Bool; public var isConfirmed: Bool }

public final class ConfidenceScorer: Sendable { public let configuration: DetectionConfiguration; public init(configuration: DetectionConfiguration = .init()) { self.configuration = configuration }
    public func score(_ s: DetectionSignals) -> (Int, Set<DetectionReason>) { var score=0; var reasons=Set<DetectionReason>(); if s.wasInVehicle { score += 20 }; if s.maxTripSpeedKmh >= configuration.minDrivingSpeedKmh { score += 10 }; if s.lowSpeedDurationSeconds >= configuration.lowSpeedConfirmationSeconds { score += 15; reasons.insert(.speedAndLocation) }; if s.transitionedVehicleToWalking { score += 20; reasons.insert(.activityTransition) }; if s.knownBluetoothDisconnected { score += 20; reasons.insert(.bluetoothDisconnect) }; if (20...100).contains(s.walkingAwayDistanceMeters) { score += 10; reasons.insert(.walkingAway) }; if s.locationStable { score += 5 }; if (1..<45).contains(s.stopDurationSeconds) { score -= 25 }; if s.drivingResumed { score -= 50 }; if s.gpsAccuracyMeters > configuration.maxGoodAccuracyMeters { score -= 15 }; if s.majorRoadOrJunction { score -= 15 }; if s.poorGpsFallbackAvailable { score += 8; reasons.insert(.poorGpsFallback) }; if reasons.count > 1 { reasons.insert(.combinedSensorFusion) }; return (min(100, max(0, score)), reasons) } }
